FROM tensorflow/tensorflow:2.3.3
RUN pip3 install sklearn
RUN pip3 install tensorboard-plugin-profile
RUN mkdir -p /tmp/dumps_logs_new
EXPOSE 6006
CMD ["/bin/sh","-c","tensorboard --logdir=/tmp/dumps_logs_new --load_fast=false --port 6006 --bind_all"]