apiVersion: v1
kind: Service
metadata:
  name: inference
  labels:
    run: inference
spec:
  type: NodePort
  ports:
  - name: servicesss
    port: 6666
    nodePort: 32529
    targetPort: 6666
    protocol: TCP
  - name: tensorboardsss
    port: 6006
    nodePort: 31886
    targetPort: 6006
    protocol: TCP
  selector:
    run: inference


    