apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  labels:
    app: task-pv
spec:
  containers:
    - name: task-pv-container
      image: image-registry.openshift-image-registry.svc:5000/fabric/nginx:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: myvolume
  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: mypvc
