---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org1
  labels:
    app: chaincode-basic-org1
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org1
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/fabric/tcmpcc:v1.0
          imagePullPolicy: Always
          name: chaincode-basic-org1
          env:
            - name: CHAINCODE_ID
              value: "basic:7df26f74ecb2f1e62c44c8358add49f982fa974fd0499358f278a0da853a2381"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
